from __future__ import annotations

QUANTS = [
    {
        "model": "unsloth/Laguna-S-2.1-GGUF:UD-IQ1_S",
        "repo": "unsloth/Laguna-S-2.1-GGUF",
        "file": "Laguna-S-2.1-UD-IQ1_S.gguf",
        "size_gib": 31.45,
        "bits": "UD-IQ1_S",
        "engine": "llama.cpp",
        "status": "tested: smallest; 0.658 quality; dominated by IQ1_M",
        "recommended": False,
    },
    {
        "model": "unsloth/Laguna-S-2.1-GGUF:UD-IQ1_M",
        "repo": "unsloth/Laguna-S-2.1-GGUF",
        "file": "Laguna-S-2.1-UD-IQ1_M.gguf",
        "size_gib": 33.19,
        "bits": "UD-IQ1_M",
        "engine": "llama.cpp",
        "status": "tested: 0.792 quality; faster than IQ1_S",
        "recommended": False,
    },
    {
        "model": "mlx-community/Laguna-S-2.1-oQ2e",
        "size_gib": 33.74,
        "bits": "2.70 effective",
        "status": "experimental",
        "recommended": True,
    },
    {
        "model": "unsloth/Laguna-S-2.1-GGUF:UD-IQ2_XXS",
        "repo": "unsloth/Laguna-S-2.1-GGUF",
        "file": "Laguna-S-2.1-UD-IQ2_XXS.gguf",
        "size_gib": 34.64,
        "bits": "UD-IQ2_XXS",
        "engine": "llama.cpp",
        "status": "tested: 0.646 quality; dominated",
        "recommended": False,
    },
    {
        "model": "unsloth/Laguna-S-2.1-GGUF:UD-IQ2_M",
        "repo": "unsloth/Laguna-S-2.1-GGUF",
        "file": "Laguna-S-2.1-UD-IQ2_M.gguf",
        "size_gib": 34.71,
        "bits": "UD-IQ2_M",
        "engine": "llama.cpp",
        "status": "tested: 0.625 quality; dominated by IQ1_M",
        "recommended": False,
    },
    {
        "model": "pipenetwork/Laguna-S-2.1-MLX-2bit",
        "size_gib": 35.17,
        "bits": "mixed 2/4/8-bit",
        "engine": "mlx-lm-custom",
        "status": "tested: 1.000 quality; fastest fixed decode",
        "recommended": True,
    },
    {
        "model": "unsloth/Laguna-S-2.1-GGUF:UD-Q2_K_XL",
        "repo": "unsloth/Laguna-S-2.1-GGUF",
        "file": "Laguna-S-2.1-UD-Q2_K_XL.gguf",
        "size_gib": 36.96,
        "bits": "UD-Q2_K_XL",
        "engine": "llama.cpp",
        "status": "tested: 0.875 quality; perfect agentic score",
        "recommended": False,
    },
    {
        "model": "unsloth/Laguna-S-2.1-GGUF:UD-IQ3_XXS",
        "repo": "unsloth/Laguna-S-2.1-GGUF",
        "file": "Laguna-S-2.1-UD-IQ3_XXS.gguf",
        "size_gib": 41.24,
        "bits": "UD-IQ3_XXS",
        "engine": "llama.cpp",
        "status": "tested: 0.708 quality; dominated by IQ1_M",
        "recommended": False,
    },
    {
        "model": "JANGQ-AI/Laguna-S-2.1-JANG_2L",
        "size_gib": 41.26,
        "bits": "mixed 2/3/6/8-bit",
        "engine": "jang-mlx",
        "status": "tested: 0.417 quality; pinned runtime adapter required",
        "recommended": False,
    },
    {
        "model": "mlx-community/Laguna-S-2.1-oQ3e",
        "size_gib": 45.86,
        "bits": "3.59 effective",
        "status": "tested: 0.625 quality; no measured advantage",
        "recommended": False,
    },
    {
        "model": "pipenetwork/Laguna-S-2.1-MLX-3bit",
        "size_gib": 47.93,
        "bits": "3-bit; router 8-bit",
        "engine": "mlx-lm-custom",
        "status": "tested: 0.875 quality; dominated by pipenetwork 2-bit",
        "recommended": False,
    },
    {
        "model": "mlx-community/Laguna-S-2.1-oQ4e",
        "size_gib": 59.73,
        "bits": "4.60 effective",
        "status": "tested: 0.875 quality; dominated by pipenetwork 2-bit",
        "recommended": False,
    },
    {
        "model": "Vontra/Laguna-S-2.1-MLX-4bit",
        "size_gib": 61.61,
        "bits": "4",
        "status": "incompatible: gate quantization shape mismatch in mlx-vlm 0.6.6",
        "recommended": False,
    },
    {
        "model": "poolside/Laguna-S-2.1-NVFP4-mlx",
        "size_gib": 66.97,
        "bits": "NVFP4",
        "status": "tested: official testing-only; 0.875 quality; slow runtime",
        "recommended": False,
    },
    {
        "model": "Vontra/Laguna-S-2.1-MLX-6bit",
        "size_gib": 88.98,
        "bits": "6",
        "status": "community; memory-margin risk",
        "recommended": False,
    },
    {
        "model": "Vontra/Laguna-S-2.1-MLX-8bit",
        "size_gib": 116.34,
        "bits": "8",
        "status": "not recommended on 128 GB",
        "recommended": False,
    },
    {
        "model": "pipenetwork/Laguna-S-2.1-MLX-4bit",
        "size_gib": 61.61,
        "bits": "4",
        "status": "incompatible: 141 unexpected router parameters in mlx-vlm 0.6.6",
        "recommended": False,
    },
    {
        "model": "pipenetwork/Laguna-S-2.1-MLX-6bit",
        "size_gib": 88.98,
        "bits": "6",
        "status": "community duplicate conversion; memory-margin risk",
        "recommended": False,
    },
    {
        "model": "pipenetwork/Laguna-S-2.1-MLX-8bit",
        "size_gib": 116.34,
        "bits": "8",
        "status": "not recommended on 128 GB; insufficient runtime headroom",
        "recommended": False,
    },
    {
        "model": "pipenetwork/Laguna-S-2.1-MLX-bf16",
        "size_gib": 0.0,
        "bits": "BF16",
        "status": "does not fit 128 GB unified memory",
        "recommended": False,
    },
    {
        "model": "poolside/Laguna-S-2.1-GGUF",
        "size_gib": 70.01,
        "bits": "Q4_K_M",
        "status": "official GGUF; llama.cpp tested; slower than small quants",
        "recommended": False,
    },
    {
        "model": "olka-fi/Laguna-S-2.1-MXFP4",
        "size_gib": 63.68,
        "bits": "MXFP4",
        "status": "not an MLX conversion; no native Metal kernel path",
        "recommended": False,
    },
    {
        "model": "poolside/Laguna-S-2.1-NVFP4",
        "size_gib": 66.97,
        "bits": "NVFP4",
        "status": "CUDA-oriented checkpoint; use the separate MLX conversion on macOS",
        "recommended": False,
    },
    {
        "model": "poolside/Laguna-S-2.1-FP8",
        "size_gib": 0.0,
        "bits": "FP8",
        "status": "CUDA-oriented checkpoint; no native MLX path tested",
        "recommended": False,
    },
    {
        "model": "poolside/Laguna-S-2.1-INT4",
        "size_gib": 0.0,
        "bits": "INT4",
        "status": "CUDA-oriented checkpoint; no native MLX path tested",
        "recommended": False,
    },
]
