from __future__ import annotations

QUANTS = [
    {
        "model": "unsloth/Laguna-S-2.1-GGUF",
        "file": "Laguna-S-2.1-UD-IQ1_M.gguf",
        "size_gib": 33.19,
        "bits": "UD-IQ1_M",
        "engine": "llama.cpp",
        "status": "community GGUF; benchmark pending",
        "recommended": False,
    },
    {
        "model": "mlx-community/Laguna-S-2.1-oQ2e",
        "size_gib": 33.74,
        "bits": "2.70 effective",
        "status": "experimental",
        "recommended": True,
    },
    {
        "model": "mlx-community/Laguna-S-2.1-oQ3e",
        "size_gib": 45.86,
        "bits": "3.59 effective",
        "status": "community; complete",
        "recommended": True,
    },
    {
        "model": "mlx-community/Laguna-S-2.1-oQ4e",
        "size_gib": 0.0,
        "bits": "4.x effective",
        "status": "upload incomplete when catalogued",
        "recommended": False,
    },
    {
        "model": "Vontra/Laguna-S-2.1-MLX-4bit",
        "size_gib": 61.61,
        "bits": "4",
        "status": "incompatible: gate quantization shape mismatch in mlx-vlm 0.6.6",
        "recommended": False,
    },
    {
        "model": "poolside/Laguna-S-2.1-NVFP4-mlx",
        "size_gib": 66.97,
        "bits": "NVFP4",
        "status": "official testing-only",
        "recommended": True,
    },
    {
        "model": "Vontra/Laguna-S-2.1-MLX-6bit",
        "size_gib": 88.98,
        "bits": "6",
        "status": "community; memory-margin risk",
        "recommended": False,
    },
    {
        "model": "Vontra/Laguna-S-2.1-MLX-8bit",
        "size_gib": 116.34,
        "bits": "8",
        "status": "not recommended on 128 GB",
        "recommended": False,
    },
    {
        "model": "pipenetwork/Laguna-S-2.1-MLX-4bit",
        "size_gib": 61.61,
        "bits": "4",
        "status": "incompatible: 141 unexpected router parameters in mlx-vlm 0.6.6",
        "recommended": False,
    },
    {
        "model": "pipenetwork/Laguna-S-2.1-MLX-6bit",
        "size_gib": 88.98,
        "bits": "6",
        "status": "community duplicate conversion; memory-margin risk",
        "recommended": False,
    },
    {
        "model": "pipenetwork/Laguna-S-2.1-MLX-8bit",
        "size_gib": 116.34,
        "bits": "8",
        "status": "not recommended on 128 GB; insufficient runtime headroom",
        "recommended": False,
    },
    {
        "model": "pipenetwork/Laguna-S-2.1-MLX-bf16",
        "size_gib": 0.0,
        "bits": "BF16",
        "status": "does not fit 128 GB unified memory",
        "recommended": False,
    },
    {
        "model": "poolside/Laguna-S-2.1-GGUF",
        "size_gib": 70.01,
        "bits": "Q4_K_M",
        "status": "official GGUF; llama.cpp tested",
        "recommended": True,
    },
    {
        "model": "olka-fi/Laguna-S-2.1-MXFP4",
        "size_gib": 63.68,
        "bits": "MXFP4",
        "status": "not an MLX conversion; no native Metal kernel path",
        "recommended": False,
    },
    {
        "model": "poolside/Laguna-S-2.1-NVFP4",
        "size_gib": 66.97,
        "bits": "NVFP4",
        "status": "CUDA-oriented checkpoint; use the separate MLX conversion on macOS",
        "recommended": False,
    },
    {
        "model": "poolside/Laguna-S-2.1-FP8",
        "size_gib": 0.0,
        "bits": "FP8",
        "status": "CUDA-oriented checkpoint; no native MLX path tested",
        "recommended": False,
    },
    {
        "model": "poolside/Laguna-S-2.1-INT4",
        "size_gib": 0.0,
        "bits": "INT4",
        "status": "CUDA-oriented checkpoint; no native MLX path tested",
        "recommended": False,
    },
]
